backend:
  name: github
  repo: ssigg/ako-netlify # Path to your Github repository
  branch: master # Branch to update
publish_mode: editorial_workflow
media_folder: "static/content"
collections:
- name: "index" # Used in routes, e.g. /admin/collections/blog
  label: "Start" # Used in the UI
  folder: "content" # The path to the folder where the documents are stored
  create: false # Allow users to create new documents in this collection
  fields: # The fields for each document, usually in front matter
    - {label: "Flyer", name: "flyer", widget: "image"}
    - {label: "Content", name: "body", widget: "markdown"}
- name: "archive" # Used in routes, e.g. /admin/collections/blog
  label: "Archive Entry" # Used in the UI
  folder: "content/archiv" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  fields: # The fields for each document, usually in front matter
    - {label: "Date", name: "date", widget: "datetime"}
    - {label: "Flyer", name: "flyer", widget: "image"}
    - {label: "Content", name: "body", widget: "markdown"}